/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	v1alpha1 "redis-priv-operator/pkg/apis/tdb/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMysqlProxies implements MysqlProxyInterface
type FakeMysqlProxies struct {
	Fake *FakeTdbV1alpha1
	ns   string
}

var mysqlproxiesResource = schema.GroupVersionResource{Group: "tdb.tongdun.net", Version: "v1alpha1", Resource: "mysqlproxies"}

var mysqlproxiesKind = schema.GroupVersionKind{Group: "tdb.tongdun.net", Version: "v1alpha1", Kind: "MysqlProxy"}

// Get takes name of the mysqlProxy, and returns the corresponding mysqlProxy object, and an error if there is any.
func (c *FakeMysqlProxies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MysqlProxy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(mysqlproxiesResource, c.ns, name), &v1alpha1.MysqlProxy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MysqlProxy), err
}

// List takes label and field selectors, and returns the list of MysqlProxies that match those selectors.
func (c *FakeMysqlProxies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MysqlProxyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(mysqlproxiesResource, mysqlproxiesKind, c.ns, opts), &v1alpha1.MysqlProxyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MysqlProxyList{ListMeta: obj.(*v1alpha1.MysqlProxyList).ListMeta}
	for _, item := range obj.(*v1alpha1.MysqlProxyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested mysqlProxies.
func (c *FakeMysqlProxies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(mysqlproxiesResource, c.ns, opts))

}

// Create takes the representation of a mysqlProxy and creates it.  Returns the server's representation of the mysqlProxy, and an error, if there is any.
func (c *FakeMysqlProxies) Create(ctx context.Context, mysqlProxy *v1alpha1.MysqlProxy, opts v1.CreateOptions) (result *v1alpha1.MysqlProxy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(mysqlproxiesResource, c.ns, mysqlProxy), &v1alpha1.MysqlProxy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MysqlProxy), err
}

// Update takes the representation of a mysqlProxy and updates it. Returns the server's representation of the mysqlProxy, and an error, if there is any.
func (c *FakeMysqlProxies) Update(ctx context.Context, mysqlProxy *v1alpha1.MysqlProxy, opts v1.UpdateOptions) (result *v1alpha1.MysqlProxy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(mysqlproxiesResource, c.ns, mysqlProxy), &v1alpha1.MysqlProxy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MysqlProxy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMysqlProxies) UpdateStatus(ctx context.Context, mysqlProxy *v1alpha1.MysqlProxy, opts v1.UpdateOptions) (*v1alpha1.MysqlProxy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(mysqlproxiesResource, "status", c.ns, mysqlProxy), &v1alpha1.MysqlProxy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MysqlProxy), err
}

// Delete takes name of the mysqlProxy and deletes it. Returns an error if one occurs.
func (c *FakeMysqlProxies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(mysqlproxiesResource, c.ns, name), &v1alpha1.MysqlProxy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMysqlProxies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(mysqlproxiesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MysqlProxyList{})
	return err
}

// Patch applies the patch and returns the patched mysqlProxy.
func (c *FakeMysqlProxies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MysqlProxy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mysqlproxiesResource, c.ns, name, pt, data, subresources...), &v1alpha1.MysqlProxy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MysqlProxy), err
}
