/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	v1alpha1 "td-redis-operator/pkg/apis/cache/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRedisStandalones implements RedisStandaloneInterface
type FakeRedisStandalones struct {
	Fake *FakeCacheV1alpha1
	ns   string
}

var redisstandalonesResource = schema.GroupVersionResource{Group: "cache.tongdun.net", Version: "v1alpha1", Resource: "redisstandalones"}

var redisstandalonesKind = schema.GroupVersionKind{Group: "cache.tongdun.net", Version: "v1alpha1", Kind: "RedisStandalone"}

// Get takes name of the redisStandalone, and returns the corresponding redisStandalone object, and an error if there is any.
func (c *FakeRedisStandalones) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RedisStandalone, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(redisstandalonesResource, c.ns, name), &v1alpha1.RedisStandalone{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RedisStandalone), err
}

// List takes label and field selectors, and returns the list of RedisStandalones that match those selectors.
func (c *FakeRedisStandalones) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RedisStandaloneList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(redisstandalonesResource, redisstandalonesKind, c.ns, opts), &v1alpha1.RedisStandaloneList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RedisStandaloneList{ListMeta: obj.(*v1alpha1.RedisStandaloneList).ListMeta}
	for _, item := range obj.(*v1alpha1.RedisStandaloneList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested redisStandalones.
func (c *FakeRedisStandalones) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(redisstandalonesResource, c.ns, opts))

}

// Create takes the representation of a redisStandalone and creates it.  Returns the server's representation of the redisStandalone, and an error, if there is any.
func (c *FakeRedisStandalones) Create(ctx context.Context, redisStandalone *v1alpha1.RedisStandalone, opts v1.CreateOptions) (result *v1alpha1.RedisStandalone, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(redisstandalonesResource, c.ns, redisStandalone), &v1alpha1.RedisStandalone{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RedisStandalone), err
}

// Update takes the representation of a redisStandalone and updates it. Returns the server's representation of the redisStandalone, and an error, if there is any.
func (c *FakeRedisStandalones) Update(ctx context.Context, redisStandalone *v1alpha1.RedisStandalone, opts v1.UpdateOptions) (result *v1alpha1.RedisStandalone, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(redisstandalonesResource, c.ns, redisStandalone), &v1alpha1.RedisStandalone{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RedisStandalone), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRedisStandalones) UpdateStatus(ctx context.Context, redisStandalone *v1alpha1.RedisStandalone, opts v1.UpdateOptions) (*v1alpha1.RedisStandalone, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(redisstandalonesResource, "status", c.ns, redisStandalone), &v1alpha1.RedisStandalone{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RedisStandalone), err
}

// Delete takes name of the redisStandalone and deletes it. Returns an error if one occurs.
func (c *FakeRedisStandalones) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(redisstandalonesResource, c.ns, name), &v1alpha1.RedisStandalone{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRedisStandalones) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(redisstandalonesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RedisStandaloneList{})
	return err
}

// Patch applies the patch and returns the patched redisStandalone.
func (c *FakeRedisStandalones) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RedisStandalone, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(redisstandalonesResource, c.ns, name, pt, data, subresources...), &v1alpha1.RedisStandalone{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RedisStandalone), err
}
