/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	cachev1alpha1 "td-redis-operator/pkg/apis/cache/v1alpha1"
	clientset "td-redis-operator/pkg/client/clientset"
	internalinterfaces "td-redis-operator/pkg/client/informers/internalinterfaces"
	v1alpha1 "td-redis-operator/pkg/client/listers/cache/v1alpha1"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// RedisStandbyInformer provides access to a shared informer and lister for
// RedisStandbies.
type RedisStandbyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.RedisStandbyLister
}

type redisStandbyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewRedisStandbyInformer constructs a new informer for RedisStandby type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRedisStandbyInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRedisStandbyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredRedisStandbyInformer constructs a new informer for RedisStandby type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRedisStandbyInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CacheV1alpha1().RedisStandbies(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CacheV1alpha1().RedisStandbies(namespace).Watch(context.TODO(), options)
			},
		},
		&cachev1alpha1.RedisStandby{},
		resyncPeriod,
		indexers,
	)
}

func (f *redisStandbyInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRedisStandbyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *redisStandbyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&cachev1alpha1.RedisStandby{}, f.defaultInformer)
}

func (f *redisStandbyInformer) Lister() v1alpha1.RedisStandbyLister {
	return v1alpha1.NewRedisStandbyLister(f.Informer().GetIndexer())
}
