/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// RedisClusterListerExpansion allows custom methods to be added to
// RedisClusterLister.
type RedisClusterListerExpansion interface{}

// RedisClusterNamespaceListerExpansion allows custom methods to be added to
// RedisClusterNamespaceLister.
type RedisClusterNamespaceListerExpansion interface{}

// RedisStandaloneListerExpansion allows custom methods to be added to
// RedisStandaloneLister.
type RedisStandaloneListerExpansion interface{}

// RedisStandaloneNamespaceListerExpansion allows custom methods to be added to
// RedisStandaloneNamespaceLister.
type RedisStandaloneNamespaceListerExpansion interface{}

// RedisStandbyListerExpansion allows custom methods to be added to
// RedisStandbyLister.
type RedisStandbyListerExpansion interface{}

// RedisStandbyNamespaceListerExpansion allows custom methods to be added to
// RedisStandbyNamespaceLister.
type RedisStandbyNamespaceListerExpansion interface{}
